
export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { patientProfile, treatmentPathways, selectedPathway } = await request.json();

    // Generate a comprehensive patient summary
    const summary = `
SANTAAN.IN FERTILITY CLINIC
PATIENT FERTILITY PATHWAY REPORT

Patient Code: ${patientProfile.patientCode}
Date Generated: ${new Date().toLocaleDateString('en-IN')}
Report Type: Comprehensive Fertility Assessment & Treatment Planning

═══════════════════════════════════════════════════════════════

PATIENT PROFILE SUMMARY
═══════════════════════════════════════════════════════════════

FEMALE PARTNER:
Age: ${patientProfile.femaleProfile.age || 'Not specified'}
Menstrual Cycle: ${patientProfile.femaleProfile.cycle || 'Not specified'}
Medical Conditions: ${(patientProfile.femaleProfile.conditions || []).join(', ') || 'None specified'}

MALE PARTNER:
Age: ${patientProfile.maleProfile.age || 'Not specified'}
Medical Conditions: ${(patientProfile.maleProfile.conditions || []).join(', ') || 'None specified'}

FERTILITY HISTORY:
Time Trying to Conceive: ${patientProfile.coupleHistory.timeTrying || 'Not specified'}
Previous Treatments: ${patientProfile.coupleHistory.previousTreatments || 'None'}

HOLISTIC ASSESSMENT:
Emotional State: ${patientProfile.holistic.emotionalState || 'Not specified'}
Financial Comfort Level: ${patientProfile.holistic.financialComfort || 'Not specified'}

═══════════════════════════════════════════════════════════════

RECOMMENDED TREATMENT PATHWAYS
═══════════════════════════════════════════════════════════════

${treatmentPathways.map((pathway: any, index: number) => `
${index + 1}. ${pathway.name.toUpperCase()}
   Success Rate: ${pathway.successRate}%
   Timeline: ${pathway.timeline}
   Estimated Cost: ₹${pathway.costMin.toLocaleString()} - ₹${pathway.costMax.toLocaleString()}
   Suitability Score: ${pathway.suitability}%
   
   Description: ${pathway.description}
   
   ADVANTAGES:
   ${pathway.pros.map((pro: string) => `   • ${pro}`).join('\n')}
   
   CONSIDERATIONS:
   ${pathway.cons.map((con: string) => `   • ${con}`).join('\n')}
   
   ${pathway.recommendation ? `Clinical Recommendation: ${pathway.recommendation}` : ''}
`).join('\n')}

═══════════════════════════════════════════════════════════════

TREATMENT RECOMMENDATION SUMMARY
═══════════════════════════════════════════════════════════════

Based on comprehensive analysis of your medical history, current profile, and 
evidence-based treatment protocols, the following approach is recommended:

PRIMARY RECOMMENDATION: ${treatmentPathways[0]?.name || 'To be determined in consultation'}
Success Probability: ${treatmentPathways[0]?.successRate || 'TBD'}%

The recommended pathway has been selected based on:
• Patient age and fertility factors
• Medical history and conditions
• Previous treatment outcomes
• Financial considerations
• Current evidence-based success rates

═══════════════════════════════════════════════════════════════

IMPORTANT DISCLAIMERS
═══════════════════════════════════════════════════════════════

1. This report is generated by AI analysis and is intended to support 
   clinical decision-making, not replace professional medical consultation.

2. Success rates are estimates based on population data and individual 
   results may vary significantly.

3. All treatment decisions should be made in consultation with your 
   fertility specialist after detailed clinical evaluation.

4. Cost estimates are approximate and may vary based on specific protocols,
   medications, and clinic policies.

5. This assessment is based on the information provided and may need 
   updates based on current test results and clinical findings.

═══════════════════════════════════════════════════════════════

NEXT STEPS
═══════════════════════════════════════════════════════════════

1. Review this report with your fertility specialist
2. Discuss any additional tests or evaluations needed
3. Consider the recommended treatment pathway options
4. Plan timing and preparation for selected treatment
5. Address any questions or concerns about the recommendations

For appointments and consultations:
Santaan.in Fertility Clinic
www.santaan.in

Report generated by AI-powered Fertility Pathway Planner
Powered by GreyBrain.ai Technology
    `;

    // Create a simple text file response
    const blob = new Blob([summary], { type: 'text/plain;charset=utf-8' });
    
    return new NextResponse(blob, {
      status: 200,
      headers: {
        'Content-Type': 'application/octet-stream',
        'Content-Disposition': `attachment; filename="${patientProfile.patientCode}_fertility_report.txt"`,
      },
    });

  } catch (error) {
    console.error('Error generating patient summary:', error);
    return NextResponse.json(
      { error: 'Failed to generate patient summary' },
      { status: 500 }
    );
  }
}
